### ISSUE TITLE
Unable to run this. Can someone please help me out? Are there any prerequisites for being able to run this?

### ISSUE THREAD

**Issue by noumxn** [watwars/Stock-prediction#23]

**Comment by watwars** [comment]
Hi, this project isn't 100% finished yet. There are still a few front-end UI stuffs to finish and probably some back-end bugs too. However, if you still want to run it, you will need to run both the backend server and the frontend React server.

For the backend
- We use npm as our package manager, so navigate into the backend folder, download npm and run `npm install` to download all packages.  Then run `npm app.js` to start the server.

For the frontend
- We use React and yarn as our package manager, so navigate into the frontend folder, download yarn and run `yarn` to download all packages. Then run `yarn start` to start the server.

Finally, navigate to localhost:3000 in your browser and you should be able to run the app.
